name: Semantic Release POC

on:
  push:
    branches:
      - main
      - release/*

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package

  release:
    name: Semantic Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/exec @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits
      - name: Run semantic-release
        run: npx semantic-release
