name: Semantic Release CI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Git identity
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"

      - name: Install semantic-release CLI and plugins
        run: |
          npm install -g semantic-release @semantic-release/exec @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits

      - name: Run semantic-release dry-run (test first)
        run: |
          npx semantic-release --dry-run
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Run semantic-release for real
        run: |
          npx semantic-release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}