release:
  runs-on: ubuntu-latest
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: |
        npm install -g semantic-release \
          @semantic-release/exec \
          @semantic-release/git \
          @semantic-release/github \
          conventional-changelog-conventionalcommits
    - name: Debug token presence
      run: echo "GH_TOKEN is ${GH_TOKEN:0:4}********"
    - name: Configure Git user
      run: |
        git config user.name "Lakshmisriram6"
        git config user.email "12345678+Lakshmisriram6@users.noreply.github.com"
    - name: Run semantic-release
      run: npx semantic-release
